"use client";

import { SideBar } from "@/app/types/sidebar";

export const sidebar: SideBar[] = [
    {
        objectId: 1,
        parentId: 0,
        objectType: "M",
        name: "Thống kê",
        description: null,
        status: 1,
        path: "/dashboard",
        isRender: "1",
        icon: null,
    },
    {
        objectId: 2,
        parentId: 0,
        objectType: "M",
        name: "Quản lý người dùng",
        description: null,
        status: 1,
        path: "/am_user",
        isRender: "1",
        icon: null,
    },
    {
        objectId: 3,
        parentId: 0,
        objectType: "M",
        name: "Quản lý khu vực",
        description: null,
        status: 1,
        path: "/area",
        isRender: "1",
        icon: null,
    },
    {
        objectId: 4,
        parentId: 0,
        objectType: "M",
        name: "Quản lý giải đấu",
        description: null,
        status: 1,
        path: "/competition",
        isRender: "1",
        icon: null,
    },
    {
        objectId: 5,
        parentId: 0,
        objectType: "M",
        name: "Quản lý mùa giải",
        description: null,
        status: 1,
        path: "/season",
        isRender: "1",
        icon: null,
    },
    {
        objectId: 6,
        parentId: 0,
        objectType: "M",
        name: "Quản lý đội",
        description: null,
        status: 1,
        path: "/team",
        isRender: "1",
        icon: null,
    },
    {
        objectId: 7,
        parentId: 0,
        objectType: "M",
        name: "Quản lý trận đấu",
        description: null,
        status: 1,
        path: "/match",
        isRender: "1",
        icon: null,
    },
];